// Run with Playwright installed, or PLAYWRIGHT_MODULE pointing to its module entry.
import { build } from 'tsdown'
import { createServer } from 'node:http'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright')
const directory = await mkdtemp(join(tmpdir(), 'security-ui-'))
let browser, server
try {
  await build({ config: false, entry: 'tests/ui/fixture.jsx', outDir: directory, format: 'iife', platform: 'browser', deps: { alwaysBundle: [/.*/] }, define: { 'process.env.NODE_ENV': '"production"' } })
  server = createServer(async (request, response) => {
    response.setHeader('Content-Type', request.url === '/fixture.js' ? 'text/javascript' : 'text/html')
    response.end(request.url === '/fixture.js' ? await readFile(join(directory, 'fixture.iife.js')) : '<!doctype html><html lang="zh"><meta charset="utf-8"><div id="root"></div><script src="/fixture.js"></script></html>')
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) })
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  const url = `http://127.0.0.1:${server.address().port}`
  await page.goto(url)
  await page.getByRole('heading', { name: '示例服务', exact: true }).waitFor()
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('任务名称', { exact: true }).fill('未保存的配置')
  await page.getByRole('button', { name: '运行记录', exact: false }).click()
  await page.getByRole('alertdialog', { name: '还有未保存的修改' }).waitFor()
  await page.getByRole('button', { name: '继续编辑' }).click()
  assert.equal(await page.getByLabel('任务名称', { exact: true }).inputValue(), '未保存的配置')
  await page.keyboard.press('Escape')
  await page.getByRole('alertdialog', { name: '还有未保存的修改' }).waitFor()
  await page.keyboard.press('Tab')
  assert.equal(await page.evaluate(() => document.activeElement.textContent), '放弃修改并离开')
  await page.keyboard.press('Tab')
  assert.equal(await page.evaluate(() => document.activeElement.textContent), '继续编辑')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: '保存任务', exact: true }).dblclick()
  assert.equal(await page.evaluate(() => window.scanFixture.saved), 1)
  await page.getByRole('heading', { name: '示例服务', exact: true }).waitFor()
  await page.evaluate(() => { window.scanFixture.offline = true })
  await page.getByText('暂时无法连接', { exact: false }).waitFor()
  await page.evaluate(() => { window.scanFixture.offline = false })
  await page.getByText('暂时无法连接', { exact: false }).waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: '查看报告', exact: true }).click()
  await page.getByRole('heading', { name: '接下来，处理扫描结果' }).waitFor()
  assert.equal(await page.getByLabel('修复交付方式', { exact: true }).inputValue(), 'pr')
  await page.getByLabel('修复交付方式', { exact: true }).selectOption('local')
  await page.getByText('在扫描目录直接修改', { exact: false }).waitFor()
  await page.getByLabel('修复交付方式', { exact: true }).selectOption('pr')
  await page.locator('.finding-picker summary').click()
  await page.getByLabel('问题类型', { exact: true }).selectOption('dependencyRisk')
  await page.getByRole('button', { name: '全选当前结果', exact: true }).click()
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 1)
  await page.getByLabel('问题类型', { exact: true }).selectOption('secretRisk')
  await page.getByText('筛选外已选 1', { exact: false }).waitFor()
  await page.getByRole('button', { name: '选取当前结果前 19', exact: true }).click()
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 19)
  await page.getByRole('button', { name: '在会话中修复 (20)', exact: true }).waitFor()
  assert.equal(await page.getByRole('checkbox', { checked: false, disabled: true }).count(), 5)
  await page.getByRole('button', { name: '取消当前结果', exact: true }).click()
  await page.getByRole('button', { name: '在会话中修复 (1)', exact: true }).waitFor()
  await page.getByRole('button', { name: '清空选择', exact: true }).click()
  await page.getByRole('button', { name: '重置筛选', exact: true }).click()
  assert.equal(await page.getByRole('checkbox').count(), 26)
  await page.getByLabel('复核状态', { exact: true }).selectOption('confirmed')
  await page.getByLabel('风险级别', { exact: true }).selectOption('medium')
  assert.equal(await page.getByRole('checkbox').count(), 0)
  assert.equal(await page.getByRole('button', { name: '全选当前结果', exact: true }).isDisabled(), true)
  await page.getByLabel('风险级别', { exact: true }).selectOption('high')
  await page.getByLabel('搜索问题或文件').fill('src/api')
  await page.getByRole('button', { name: '全选当前结果', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  if (process.env.UI_SCREENSHOT) await page.screenshot({ path: process.env.UI_SCREENSHOT.replace('.png', '-selection.png'), fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.evaluate(() => { window.scanFixture.prError = 'repair-pr-dirty' })
  await page.getByRole('button', { name: '刷新交付状态', exact: true }).click()
  await page.getByText('仓库包含未提交修改', { exact: false }).waitFor()
  assert.equal(await page.getByRole('button', { name: '在会话中修复 (1)', exact: true }).isDisabled(), true)
  await page.getByLabel('修复交付方式', { exact: true }).selectOption('local')
  assert.equal(await page.getByRole('button', { name: '修复选中问题 (1)', exact: true }).isEnabled(), true)
  await page.getByLabel('修复交付方式', { exact: true }).selectOption('pr')
  await page.evaluate(() => { window.scanFixture.prError = undefined })
  await page.getByRole('button', { name: '刷新交付状态', exact: true }).click()
  await page.getByRole('button', { name: '在会话中修复 (1)', exact: true }).click()
  await page.getByRole('button', { name: '打开修复会话', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => window.scanFixture.calls), [{ repair: ['one'], mode: 'pr', expectedRevision: 'b'.repeat(64) }, { session: 'repair-session' }])
  if (process.env.UI_SCREENSHOT) await page.screenshot({ path: process.env.UI_SCREENSHOT, fullPage: true })
  assert.equal(await page.getByRole('link', { name: '查看 PR 差异' }).getAttribute('href'), 'https://github.com/example/project/pull/1')
  await page.getByRole('button', { name: '复扫修复分支', exact: true }).click()
  await page.getByText('复扫', { exact: true }).waitFor()
  await page.getByRole('button', { name: '需关注', exact: true }).click()
  await page.getByText('没有匹配结果，试试其他筛选条件。', { exact: true }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '扫描任务', exact: false }).click()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  if (process.env.UI_SCREENSHOT) await page.screenshot({ path: process.env.UI_SCREENSHOT.replace('.png', '-mobile.png'), fullPage: true })
  assert.deepEqual(errors, [])
  console.log('UI smoke passed: draft protection, double-submit, reconnect, selection, repair, rescan, filters, mobile overflow.')
} finally { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); await rm(directory, { recursive: true, force: true }) }
